name: "Nixpkgs, Linux, GHCJS"

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Every day at 05:45
    - cron: "45 05 * * *"

env:
  useRev: "true"
  rev: "nixos-unstable"
  cachixAccount: "haskell-with-nixpkgs"
  # GitHub secret
  CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
  linkWithGold: "true"
  compiler: "ghcjs"
  ghcjsTmpLogFile: "/tmp/ghcjsTmpLogFile.log"
  ghcjsLogTailLength: "10000"

jobs:
  build10:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v10
    - name: Determined Nix-build
      run: ./build.sh
