name: "Direct import & build inside Nixpkgs"

on:
  release:
    # created: a draft is saved, or a release or pre-release is published without previously being saved as a draft
    types: [ created ]

jobs:

  build10:
    name: "Clean integration test"
    runs-on: ubuntu-latest
    steps:
    - name: "Git checkout"
      uses: actions/checkout@v3
    - name: "Local cache"
      uses: actions/cache@v3
      with:
        path: |
          /nix/store
        key: ${{ runner.os }}-Nixpkgs-integration-test
    - name: "Install Nix"
      uses: cachix/install-nix-action@v17
      with:
        nix_path: "nixpkgs=channel:nixos-unstable"
    - name: "Run Nixpkgs integration test"
      uses: Anton-Latukha/test-haskell-nixpkgs-integration-action@v1
